set nocompatible

call plug#begin('~/.vim/plugged')

" GitHub modules
Plug 'Valloric/ListToggle'
Plug 'Valloric/python-indent', { 'for': 'python' }
Plug 'Valloric/vim-indent-guides'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'ervandew/supertab'
Plug 'fatih/vim-go', { 'for': 'go' }
Plug 'jgdavey/tslime.vim'
Plug 'morhetz/gruvbox'
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-markdown'
Plug 'tpope/vim-surround'
" vim-scripts
Plug 'YankRing.vim'
Plug 'gnupg.vim'
Plug 'python.vim', { 'for': 'python' }
Plug 'python_match.vim', { 'for': 'python' }
Plug 'tex_autoclose.vim', { 'for': 'tex' }

" end of vundle configuration
call plug#end()

syntax on
set backspace=2     " allow backspacing over everything in insert mode
set laststatus=2    " always a status line
set statusline=%<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P
set showmatch       " briefly jump to matching bracket
set wildmenu        " enhanced completion in command-line
set wildignore=*.o,*.pyc,*.swp    " ignore some files when completing
set autoindent      " always set autoindenting on
set copyindent      " copy the previous indentation on autoindenting
set guifont=DejaVu\ Sans\ Mono\ 9
set guioptions-=m   " no menubar
set guioptions-=T   " no toolbar
set guioptions-=r   " no scrollbar
set hlsearch        " highlight search
set incsearch       " incremental search
set ignorecase      " case-smart searching
set smartcase       " ignore case if search pattern is all lowercase,
                    "    case-sensitive otherwise
set hidden          " set hidden buffers (to switch buffer without saving it)
set shiftround 	    " use multiple of shiftwidth when indenting with '<' and '>'
set smarttab        " insert tabs on the start of a line according to
                    "    shiftwidth, not tabstop
set nobackup        " no backups
set directory=~/tmp/vim/swap   " swap files
set complete-=i     " do not scan included files for completion
set undofile        " save undo history
set undolevels=1000 " number of changes to keep
set undodir=~/tmp/vim/undo     " where to save undo files

" colorscheme
set t_Co=256
set background=dark
colorscheme gruvbox

" extended % matching
runtime macros/matchit.vim

" swap ' with `
nnoremap ' `
nnoremap ` '

let mapleader = ","
let maplocalleader = ","

map <C-Tab> :bnext<CR>
map <S-C-Tab> :bprevious<CR>

" toggle highlight search
nmap <silent> <leader>n :silent :nohlsearch<CR>

" show spaces
set listchars=tab:>-,trail:·,eol:$
nmap <silent> <leader>s :set nolist!<CR>

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" enable indent plugin
filetype plugin on
filetype plugin indent on

" map F7 to make, cn to :cnext and cp to :cprevious
nmap <silent> <F7> :make<CR>
nmap <silent> cn :cnext<CR>
nmap <silent> cp :cprevious<CR>

" switch to paste mode with F2
set pastetoggle=<F2>

" select latest visual selection
map <leader>v V`]

" apply macro to visual selection
xnoremap @ :<C-u>call ExecuteMacroOverVisualRange()<CR>

function! ExecuteMacroOverVisualRange()
    echo "@".getcmdline()
    execute ":'<,'>normal @".nr2char(getchar())
endfunction

" CtrlP
let g:ctrlp_map = '<Leader>t'
let g:ctrlp_dotfiles = 0
let g:ctrlp_working_path_mode = 0
nmap <silent> <leader>b :CtrlPBuffer<CR>

" tslime.vim
vmap <C-c><C-c> <Plug>SendSelectionToTmux
nmap <C-c><C-c> <Plug>NormalModeSendToTmux
nmap <C-c>r <Plug>SetTmuxVars

" vim-indent-guides
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_color_change_percent = 7

" YankRing
let g:yankring_history_dir = '~/tmp/vim'
" no single char in the yankring
let g:yankring_min_element_length = 2
let g:yankring_window_height = 14
nnoremap <leader>r :YRShow<CR>

" vim-go
let g:go_fmt_command = "goimports"
